### ISSUE TITLE
[bug] Checker fails with some comprehensions 

### ISSUE THREAD

**Issue by caph1993** [tillahoffmann/localscope#6]
The minimal example below raises `NameError: 'n' is not in globals` and it should not.
```python
@localscope
def f(n):
    return [n for i in range(n)]
```

**Comment by tillahoffmann** [comment]
Interesting, using the variable `n` in the list comprehension seems to change how it is resolved in the higher scope (i.e. the scope of `f`). I don't have an immediate fix for this, but hopefully, the folks on StackOverflow will be able to answer [this question](https://stackoverflow.com/q/64480167/1150961).

**Comment by tillahoffmann** [comment]
@caph1993, should be fixed in v0.1.3. Thanks for reporting.
